---
- name: Install Apache and Upload my Web Page
  hosts: lin
  become: yes

  vars:
    mytext: "Privet ot DevOps"

  tasks:

  - name: Ping my servers
    ping:

  # - name: Unregister Server from Load Balancer
  #   shell: pwd >> /tmp/log.txt
  #   delegate_to: 127.0.0.1
  # "." is playbook directory for localhost, home directory ansible user for remotehost

  - name: Unregister Server from Load Balancer
    shell: echo This server {{ inventory_hostname }} was unregistred from our Load Balancer, node name is {{ ansible_nodename }} >> ./log.txt
    delegate_to: 127.0.0.1

  - name: Update my Database
    shell: echo UPDATING Database... && sleep 5
    run_once: true

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is fileN1
        On ENGLISH Hello World
        On RUSSIAN {{ mytext }}
    delegate_to: linux1
    
  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
        This is fileN2
        On ENGLISH Hello World
        On RUSSIAN {{ mytext }}

  # - name: Reboot my servers
  #   shell: sleep 3 && reboot now
  #   async: 1
  #   pool: 0
  #   ignore_errors: true
  # - name: Wait till my servers will come up oonline
  #   wait_for:
  #     host: "{{ inventory_hostname }}"
  #     state: started
  #     delay: 5
  #     timeout: 40
  #     delegate_to: 127.0.0.1
  
  # not worked
    
  - name: Unconditionally reboot the machine with all defaults
    reboot:

  # - name: Reboot a slow machine that might have lots of updates to apply
  #   reboot:
  #     reboot_timeout: 3600

  - shell: uptime
    register: results

  - debug: var=results

  

...
