---
- name: Install Apache and Upload my Web Page
  hosts: lin
  become: yes

  vars:
    message1: Hello
    message2: World
    message3: "!!!"

    execute: false

  tasks:

  - import_tasks: playbook12_include.yml #static
    vars:
      message3: "-import1"
      message4: "static"

  - include:  playbook12_include_2.yml # set execute

  - include: playbook12_include.yml message3="-include1" #dinamic

  - set_fact: message2="WORLD"

  - import_tasks: playbook12_include.yml
    vars:
      message3: "-import2"
    when: execute
  
  - include: playbook12_include.yml message3="-include2"
    when: execute

...
