---

- name: Loops Playbook
  hosts: lin
  become: yes

  tasks:
  - name: Say Hello to All
    debug: msg="Hello {{ item }}!"    
    loop: # with_items: fof ansible<= 2.4
      - "Vasya"
      - "Petya"
      - "Masha"
  
  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 1
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print output
    debug:
      var: output.stdout

  # - name: Install many packages
  #   yum: name={{ item }} state=latest
  #   with_items:
  #     - python
  #     - tree
  #     - mysql-client

...
